export default {
  VALIDATE: 'survey/VALIDATE',
  SUBMITTED: 'survey/SUBMITTED',
  SUBMITTING: 'survey/SUBMITTING',
  REQUEST_SURVEY: 'survey/REQUEST_SURVEY',
  LOAD_SURVEY: 'survey/LOAD_SURVEY',
  SYNC_RESPONSES: 'survey/SYNC_RESPONSES',
  SYNC_STATS: 'survey/SYNC_STATS',
  LOAD_RESPONSE: 'survey/LOAD_RESPONSE',
  ADD_RATING: 'survey/ADD_RATING',
  SAVE_RESPONSE: 'survey/SAVE_RESPONSE',
  SET_ERROR: 'survey/SET_ERROR',
  RESET_ERROR: 'survey/RESET_ERROR',
  RESET_ALL_ERRORS: 'survey/RESET_ALL_ERRORS'
};
